//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockStreet.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeExecution
    {
        public int tradeId { get; set; }
        public string symbol { get; set; }
        public int tradedQuantity { get; set; }
        public decimal tradePrice { get; set; }
        public int remainingOrderQuantity { get; set; }
        public int blockId { get; set; }
        public System.DateTime timestamp { get; set; }
        public string status { get; set; }
    
        public virtual ExternalBlock ExternalBlock { get; set; }
    }
}
